#This Ansible playbook is designed to perform a basic reconnaissance ("recce") on remote hosts, gathering OS version information and saving the results locally on the control machine
---
- name: OS Information
  hosts: all,!localhost,!127.0.0.1 #Target all remote hosts EXCEPT localhost
  connection: paramiko # Use paramiko SSH instead of default OpenSSH
  gather_facts: no # Skip automatic fact gathering
  become: no #Do not escalate privileges
  ignore_errors: yes # Don't stop if a host has errors
    
  tasks:
  - name: Get version information
    raw: 'echo {{ inventory_hostname }}: $HOSTNAME && cat /etc/*release* 2>/dev/null || cat /etc/*version* 2>/dev/null || echo Unknown'
    register: info
    changed_when: False

  - name: Ensure recce path exists
    local_action: file dest=~/.ansible/files/recce state=directory
    run_once: yes 

  - name: Write info to file
    local_action: "shell echo '{{ info.stdout }}' >> ~/.ansible/files/recce/hostinfo.txt"
